server {
    listen 80;
    listen [::]:80;

    server_name persona.skb-prime.web.id;

    # ======================================
    # Laravel Public Directory
    # ======================================
    root /var/www/html/public;

    index index.php index.html;

    charset utf-8;

    # ======================================
    # Laravel
    # ======================================
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # ======================================
    # PHP-FPM
    # ======================================
    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass 127.0.0.1:9000;

        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        # Prevent HTTPoxy vulnerability
        fastcgi_param HTTP_PROXY "";

        # HTTPS information
        fastcgi_param HTTPS $https if_not_empty;
    }

    # ======================================
    # Deny hidden files
    # ======================================
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # ======================================
    # Upload limit
    # ======================================
    client_max_body_size 50M;

    # ======================================
    # Cache static files
    # ======================================
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf)$ {
        expires 7d;
        access_log off;

        try_files $uri =404;
    }
}